language: csharp
solution: fantasia.sln
install:
  - nuget restore Qet/fastasia.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release fantasia.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ports.tests/bin/Release/ports.tests.dll


